# arxivの学問領域の指定
subject: 'cat:cs.*'

# 検索キーワード
keywords:
        MLOps: 10
        Machine Learning Operations: 10
        Machine Learning Systems Engineering: 10
        Meta learning: 10
        Meta-learning: 10
        Meta features: 10
        Meta-features: 10
        algorithm selection: 5
        exploratory landscape analysis: 5
        kaggle: 3
        resnet: 3

# 通知の閾値
score_threshold: 0
