# arxivの学問領域の指定
subject: 'cat:cs.*'

# 検索キーワード
keywords:
        XAI: 10
        Explainable Artificial Intelligence: 10
        eXplainabale AI: 10
        explainable artificial intelligence: 10
        kaggle: 3
        resnet: 3

# 通知の閾値
score_threshold: 0
